[package]
name = "dasha"
version = "0.1.0"
authors = ["William Tange <will@brt.sexy>"]
edition = "2018"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = [
    "prepush-hook",
    "precommit-hook",
    "run-cargo-test",
    "run-cargo-clippy",
    "run-cargo-fmt",
]
