name: dispatch

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: curl -XPOST "https://api.github.com/repos/disassemb-ly/disassemb-ly.github.io/actions/workflows/pages.yml/dispatches" --data '{"ref":"main"}'
